# Generated by Django 2.0 on 2019-06-11 11:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuideDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='指南title', max_length=10, verbose_name='指南title')),
                ('link', models.CharField(help_text='指南链接', max_length=100, verbose_name='指南链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '国学指南值详情信息',
                'verbose_name_plural': '国学指南值详情信息',
                'db_table': 'GX_guide_detail',
            },
        ),
        migrations.CreateModel(
            name='GuideType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('guide_type', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目')], help_text='类目级别', verbose_name='类目级别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('parent_guide', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_guide', to='guide.GuideType', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '国学指南之版块类别',
                'verbose_name_plural': '国学指南之版块类别',
                'db_table': 'GX_guide_type',
            },
        ),
        migrations.AddField(
            model_name='guidedetail',
            name='guide_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='guide_detail', to='guide.GuideType', verbose_name='所属类别'),
        ),
    ]
