# Generated by Django 2.0 on 2019-06-11 11:38

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('author_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='作者姓名')),
                ('author_link', models.CharField(blank=True, max_length=30, null=True, verbose_name='作者简介链接')),
                ('img_link', models.ImageField(blank=True, null=True, upload_to='daodus/book_images', verbose_name='文章图片')),
                ('browse_count', models.IntegerField(blank=True, default=0, verbose_name='浏览量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '文章详情',
                'verbose_name_plural': '文章详情',
                'db_table': 'GX_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='文章内容')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_content', to='articles.Article', verbose_name='所属文章')),
            ],
            options={
                'verbose_name': '文章内容',
                'verbose_name_plural': '文章内容',
                'db_table': 'GX_article_content',
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='类别名', max_length=30, null=True, verbose_name='类别名')),
                ('type_desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='类别描述信息')),
                ('article_types', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], help_text='类目级别', verbose_name='类目级别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('parent_article', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_acticle', to='articles.ArticleType', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
                'db_table': 'GX_article_type',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('img_link', models.ImageField(blank=True, null=True, upload_to='article/images', verbose_name='人物头像')),
                ('birth_place', models.CharField(blank=True, max_length=20, null=True, verbose_name='籍贯')),
                ('life_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='生卒')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='简述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('article_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='articles.ArticleType', verbose_name='所属类别')),
            ],
            options={
                'verbose_name': '国学人物介绍',
                'verbose_name_plural': '国学人物介绍',
                'db_table': 'GX_person',
            },
        ),
        migrations.CreateModel(
            name='PersonContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='人物生平')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_content', to='articles.Person', verbose_name='所属人物')),
            ],
            options={
                'verbose_name': '人物介绍',
                'verbose_name_plural': '人物介绍',
                'db_table': 'GX_person_content',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='articles.ArticleType', verbose_name='所属类别'),
        ),
    ]
