# Generated by Django 2.0 on 2019-06-11 11:43

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='帖子内容')),
            ],
            options={
                'verbose_name': '帖子内容详情',
                'verbose_name_plural': '帖子内容详情',
                'db_table': 'GX_forum_content',
            },
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='回复内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='回复时间')),
                ('last_reply_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回复人')),
            ],
            options={
                'verbose_name': '帖子回复',
                'verbose_name_plural': '帖子回复',
                'db_table': 'GX_forum_reply',
            },
        ),
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='帖子标题', max_length=50, verbose_name='帖子标题')),
                ('browse_count', models.IntegerField(blank=True, default=0, help_text='帖子浏览量', null=True, verbose_name='浏览量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('last_reply_time', models.DateTimeField(auto_now=True, verbose_name='最后发表时间')),
                ('author', models.ForeignKey(help_text='帖子作者', on_delete=django.db.models.deletion.CASCADE, related_name='author_forum', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '帖子主题',
                'verbose_name_plural': '帖子主题',
                'db_table': 'GX_forum_topic',
            },
        ),
        migrations.CreateModel(
            name='ForumType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('forum_type', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目')], help_text='类目级别', verbose_name='类目级别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('parent_forum', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_forum', to='forums.ForumType', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '论坛版块类别',
                'verbose_name_plural': '论坛版块类别',
                'db_table': 'GX_forum_type',
            },
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='forum_type',
            field=models.ForeignKey(help_text='帖子类型', on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic', to='forums.ForumType', verbose_name='所属类别'),
        ),
        migrations.AddField(
            model_name='forumreply',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reply', to='forums.ForumTopic', verbose_name='所属帖子主题'),
        ),
        migrations.AddField(
            model_name='forumcontent',
            name='topic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='forum_content', to='forums.ForumTopic', verbose_name='所属帖子主题'),
        ),
    ]
